### PR TITLE
Update partner list with RUDAZ

### PR DESCRIPTION
**Pull request by kalbermattenm**
Title says it all, just a link to vsgis.

Merging

### CODE REVIEW

**Comment by rbovard** [comment]
Is it really based on GMF (I saw Autodesk logo on loading...)?

And I think the links are *more or less* sorted alphabetically, no?

**Comment by kalbermattenm** [comment]
I think it is an ongoing work (I was asked by Benjamin from RUDAZ to add them to the list...)

**Comment by rbovard** [comment]
Mmmh ok, so would't be better to add link to this gemeinde?

By the way, you should also update https://github.com/geomapfish/geomapfish_website to be up-to-date.

**Comment by kalbermattenm** [comment]
> Mmmh ok, so would't be better to add link to this gemeinde?

Not sure it is the only one which is running on GMF...

I will not have time to test each Gemeinde to check if it is running on GMF (or not...).

> By the way, you should also update https://github.com/geomapfish/geomapfish_website to be up-to-date.

Yes, by the way I would like to go on with that (or, should I say, try to finish something...)

**Pull request merged**
